/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 unity_logo.glb -T 
Files: unity_logo.glb [12.28KB] > C:\Users\javie\Documents\Software\portfolio\3d-portfolio\public\models\unity_logo-transformed.glb [2.11KB] (83%)
Author: AntonioModer (https://sketchfab.com/AntonioModer)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/unity-logo-3d-mesh-2afd04b26ca64c6b8392f75e217ffdb9
Title: Unity logo 3D mesh
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Unity(props) {
  const { nodes, materials } = useGLTF('models/unity_logo-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Unity_3DLogo_Material_0.geometry} material={materials.Material} rotation={[-Math.PI / 2, 0, 0]} />
    </group>
  )
}

useGLTF.preload('models/unity_logo-transformed.glb')
