/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 typewriter.glb -T 
Files: typewriter.glb [567.79KB] > C:\Users\javie\GitHub\3d-portfolio\public\models\typewriter-transformed.glb [37.71KB] (93%)
Author: Cool_frog (https://sketchfab.com/Ettesions)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/typewriter-hw-45af87a4d7af4bf7973a7c93a79439c0
Title: typewriter -HW
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Typewriter(props) {
  const { nodes, materials } = useGLTF('/models/typewriter-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Cube001__0.geometry} material={materials['Cube.001__0']} position={[-1.444, 0.189, 0.526]} rotation={[-Math.PI / 2, 0, 0]} scale={0.346} />
      <mesh geometry={nodes.Cylinder_Material001_0.geometry} material={materials['Material.001']} position={[-0.03, 1.034, -1.749]} rotation={[-Math.PI / 2, Math.PI / 2, 0]} scale={[0.048, 0.048, 1.89]} />
      <mesh geometry={nodes.Cube023_Material_0.geometry} material={materials.Material} position={[-0.017, 0, 0]} rotation={[-Math.PI / 2, 0, 0]} scale={[1.723, 1.938, 0.178]} />
    </group>
  )
}

useGLTF.preload('/models/typewriter-transformed.glb')
